### ISSUE TITLE
Hei Sur, I hab proglem

### ISSUE THREAD

**Issue by davidtrpcevski** [CraZyLegenD/Android-Crypto-Utilities#1]
Namaste sur,

I hab proglem with ur program. Plz fix

**Comment by CraZyLegenD** [comment]
plz pull reqz onleh
no lazy 
no Imbiamba Jombes

**Comment by davidtrpcevski** [comment]
Sur y cloze proglem? yez i do pull reqz butt fix proglem. thenx u sur
